remote_theme: zendesk/jekyll-theme-zendesk-garden@main
title: Schottland YMCA Sharks Swim Meet Procedures
sidebar:
  - overview
  - timers
  - label: Console Operations
    children:
      - console
      - console-adv
  - label: Computer Operations
      - computer-entries
      - computer-run-meet
