remote_theme: just-the-docs/just-the-docs
title: Schottland YMCA Sharks Swim Meet Procedures
sidebar:
  - overview
  - timers
  - label: Console Operations
    children:
      - console
      - console-adv
  - label: Computer Operations
    children:
      - computer-entries
      - computer-run-meet
