remote_theme: zendesk/jekyll-theme-zendesk-garden@main
title: Schottland YMCA Sharks Swim Meet Procedures
sidebar:
  - overview
  - timers
  - label: Console Operator
    children:
      - console
      - console-adv
  - computer
