remote_theme: just-the-docs/just-the-docs
title: Sharks Meet Procedures
nav_enabled: true
sidebar:
  - overview
  - timers
  - label: Console Operations
    children:
      - console
      - console-adv
  - label: Computer Operations
    children:
      - computer-entries
      - computer-run-meeta
  - resources
